// <auto-generated />
using System;
using KiiBlog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiiBlog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113154025_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KiiBlog.Domain.Entities.FLEX", b =>
                {
                    b.Property<int>("FLEX_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FLEX_ID"));

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("FLEX_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FLEX_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("FLEX_ID");

                    b.HasIndex("FLEX_CODE");

                    b.ToTable("FLEX", (string)null);
                });

            modelBuilder.Entity("KiiBlog.Domain.Entities.FLEX_ITEM", b =>
                {
                    b.Property<int>("FLEX_ITEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FLEX_ITEM_ID"));

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("FLEX_ID")
                        .HasColumnType("int");

                    b.Property<string>("FLEX_ITEM_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FLEX_ITEM_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("FLEX_ITEM_ID");

                    b.HasIndex("FLEX_ID");

                    b.HasIndex("FLEX_ITEM_CODE");

                    b.ToTable("FLEX_ITEM", (string)null);
                });

            modelBuilder.Entity("KiiBlog.Domain.Entities.PLAYER", b =>
                {
                    b.Property<int>("PLAYER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PLAYER_ID"));

                    b.Property<string>("CONTRACT_TYPE_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CONTRACT_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<string>("CONTRACT_TYPE_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CREATED_BY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_DELETE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LAST_UPDATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("LAST_UPDATE_ID")
                        .HasColumnType("int");

                    b.Property<string>("PLAYER_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PLAYER_NO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PLAYER_PROFILE")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<Guid>("ROW_UN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("TRANSFER_STATUS_CODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TRANSFER_STATUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("TRANSFER_STATUS_NAME")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("PLAYER_ID");

                    b.HasIndex("PLAYER_NAME");

                    b.ToTable("PLAYER", (string)null);
                });

            modelBuilder.Entity("KiiBlog.Domain.Entities.FLEX_ITEM", b =>
                {
                    b.HasOne("KiiBlog.Domain.Entities.FLEX", "FLEX")
                        .WithMany("FLEX_ITEM")
                        .HasForeignKey("FLEX_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FLEX");
                });

            modelBuilder.Entity("KiiBlog.Domain.Entities.FLEX", b =>
                {
                    b.Navigation("FLEX_ITEM");
                });
#pragma warning restore 612, 618
        }
    }
}
